name: commerce_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  badges: ^3.1.2
  carousel_slider: ^5.0.0
  fl_chart: ^0.45.1
  cloudinary_public: ^0.23.1
  dotted_border: ^2.1.0
  file_picker: ^8.1.3
  flutter_rating_bar: ^4.0.1
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  pay: ^1.0.9
  charts_flutter: ^0.12.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
